title: rpi-python-google-aiy
hero_image: images/banner.png
subtitle: rpi-python-google-aiy subtitle
description: rpi-python-google-aiy description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
