title: Control LEDs with your voice
hero_image: images/banner.png
description: Use Google Voice AIY to control LEDs
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Introduction
  - title: What you will need
  - title: Solder on the pins 
  - title: Assemble the hardware
  - title: Install the software
  - title: Setting up the Assistant API
  - title: Test the API
  - title: Simple voice responses
  - title: Making your own actions
  - title: Controlling an LED
  - title: Getting some feedback
  - title: Using voice_command
  - title: What Next?

